### ISSUE TITLE
Limper Science 101

### ISSUE THREAD

**Issue by LimperScience** [TMPierpont/timsBasicHeatmap#2]
Can you make samples, counts, and volume not case sensitive. For example, the programs needs them to be samples, counts, Volume. Otherwise, the program package does not run properly. Also,  can it be volumes instead of volume for consistency sake?

**Comment by TMPierpont** [comment]
These columns can now be set to anything by using
samples=
counts=
volumes=

Also added detection of numeric sample IDs and auto conversion from 1 to 01 or 001 etc dependent on the highest numbered sample.
