### ISSUE TITLE
Heatmap

### ISSUE THREAD

**Issue by LimperScience** [TMPierpont/timsBasicHeatmap#7]
When generating the heatmap, I'm not sure which box (left or right) is male or female. Maybe a key could be added? Also, the heatmap code on the right does not show up. Including this would allow the viewer to determine what is up- or down- regualted.

**Comment by TMPierpont** [comment]
Now it will print out the order of sub boxes as long as the matrices have names (the dataCruncher function gives them names based on the subgroup, like males females, but you can do it manually if you input the data your processed yourself)

There's also a legend finally! legend=TRUE to add it. legend_coords=c(x,y) for placement, and legend_dims=c(w,h) for size. Both have defaults, though. You control the range of the heatmap with range= the range you want the colors to max out at, and it's default is 1.
